### ISSUE TITLE
Add-on installed, but not visible in Dope Sheet; Blender 3.3.1, Windows 11

### ISSUE THREAD

**Issue by SongCast** [Pullusb/sound_waveform_display#4]
Hi, I'm trying Sound Waveform Display for the first time in Blender 3.3.1, Windows 11 and following the tutorial video at https://www.youtube.com/watch?v=N7i5m417wGY&t=6s. Problem: I cannot get the Display waveform option menu to display. Did I miss a step? Thanks.

![sound_waveform_display_debug](https://user-images.githubusercontent.com/95632470/205954247-da1a0414-8b22-4bea-9aca-05ce866ec08f.jpg)

**Comment by Pullusb** [comment]
Hi, since you are on windows and the panel isn't showing up you should have an error in console

try to use menu `Window > Show console` and check for a Traceback error, then screenshot or copy paste here

**Comment by SongCast** [comment]
Hi again. I figured it out. It's all good! :)

The issue is that I filter my add-ons by workspace, and I had not enabled it in my Dope Sheet workspace. Thanks again!

**Comment by Pullusb** [comment]
Nice, I like when problems auto-resolves ;)
