### ISSUE TITLE
Can I bundle this with my add on

### ISSUE THREAD

**Issue by mjoe67886** [Pullusb/sound_waveform_display#7]
I have the fast animation studio tools add on on blender market can I bundle this awesome code with my add on and have my add on automatically install it and enable it.. It's a free add on so I just wondered if that was a big deal if you have any advertising ventures or something or some you want me to add like to promote yourself let me know and I will...

**Comment by mjoe67886** [comment]
[](url)
[FAST_V5_4_3_BETA.zip](https://github.com/Pullusb/sound_waveform_display/files/11998054/FAST_V5_4_3_BETA.zip)
Here's a free copy it's free for life with all updates for free has almost 200 operators this is like the best thing ever next to extreme PBR and transportation of course

**Comment by Pullusb** [comment]
Hi,
I'm sorry but you can't.
I sell my addon on Blender: Market https://blendermarket.com/products/sound-waveform-display

Have a nice day.

**Comment by mjoe67886** [comment]
OK coming soon in an update then then I'll go ahead and put a button to
your add on in my recommended add-ons
list I already have a bunch in there but then people could download it and
install it and the button will also help keep
it enabled once they purchased it if you could supply me a discount code
then like I do with other add-ons in my add-on
i'll make it so when you click the button and it opens up the web page
it'll copies a discount code to the clipboard and lets you know

**Comment by Pullusb** [comment]
I won't provide discount code.
It's fine if you add a simple link to the Blender market page and/or github repository.
Just don't bundle it, thank you.

**Comment by mjoe67886** [comment]
Ok, thank you. will do!
